import re

# Read current_pip.txt
pip_packages = {}
with open("current_pip.txt", "r") as f:
    for line in f:
        line = line.strip()
        if line and not line.startswith("Package") and not line.startswith("---"):
            parts = line.split()
            if len(parts) >= 2:
                pkg_name = parts[0].lower().replace("_", "-")
                version = parts[1]
                if version != "project" and not version.startswith("C:"):
                    pip_packages[pkg_name] = version

# Read pyproject.toml
pyproject_packages = {}
with open("pyproject.toml", "r") as f:
    content = f.read()
    # Find dependencies section
    deps_match = re.search(r"dependencies\s*=\s*\[(.*?)\]", content, re.DOTALL)
    if deps_match:
        deps_content = deps_match.group(1)
        # Parse each dependency line
        for line in deps_content.split("\n"):
            line = line.strip()
            if line.startswith('"') and not line.startswith("#"):
                # Extract package name and version
                match = re.match(r'"([^=<>!@\[]+)([^"]*)"', line)
                if match:
                    pkg_name = match.group(1).lower().replace("_", "-")
                    version_spec = match.group(2)
                    pyproject_packages[pkg_name] = version_spec

# Compare
missing_in_pyproject = []
version_mismatches = []
critical_packages = []

# Critical packages to check
critical = [
    "absl-py",
    "accessible-pygments",
    "ailment",
    "aiobotocore",
    "aiohappyeyeballs",
    "aiohttp-cors",
    "aioitertools",
    "aioquic",
    "aiosignal",
    "alabaster",
    "altgraph",
    "annotated-types",
    "antlr4-python3-runtime",
    "anyio",
    "appdirs",
    "archinfo",
    "argon2-cffi",
    "argon2-cffi-bindings",
    "asciimatics",
    "asgiref",
    "astroid",
    "asttokens",
    "astunparse",
    "attrs",
    "autopep8",
    "azure-core",
    "babel",
    "backcall",
    "bcrypt",
    "beautifulsoup4",
    "billiard",
    "bitarray",
    "bitstring",
    "black",
    "bleach",
    "blinker",
    "bokeh",
    "botocore",
    "brotli",
    "cached-property",
    "certifi",
    "cfgv",
    "chardet",
    "charset-normalizer",
    "circuitbreaker",
    "ciso8601",
    "cle",
    "click-didyoumean",
    "click-plugins",
    "click-repl",
    "cloudpickle",
    "colorama",
    "colored-traceback",
    "coloredlogs",
    "colorful",
    "contourpy",
    "coverage",
    "cppheaderparser",
    "cssselect2",
    "cycler",
    "cytoolz",
    "dacite",
    "decorator",
    "deprecated",
    "detect-secrets",
    "dill",
    "diskcache",
    "distlib",
    "distributed",
    "distro",
    "dnspython",
    "docopt",
    "docutils",
    "dropbox",
    "email-validator",
    "enum-compat",
    "exceptiongroup",
    "execnet",
    "executing",
    "fastapi-cli",
    "fastjsonschema",
    "filelock",
    "first",
    "flatbuffers",
    "fonttools",
    "freetype-py",
    "frozenlist",
    "furo",
    "fusepy",
    "future",
    "gast",
    "gevent",
    "gitdb",
    "glob2",
    "google-api-core",
    "google-auth-oauthlib",
    "google-crc32c",
    "google-pasta",
    "google-resumable-media",
    "googleapis-common-protos",
    "greenlet",
    "grpcio",
    "h11",
    "h2",
    "h5py",
    "hpack",
    "httpcore",
    "httptools",
    "httpx",
    "humanfriendly",
    "identify",
    "imagesize",
    "importlib-resources",
    "iniconfig",
    "intervaltree",
    "ipython",
    "isodate",
    "isort",
    "itanium-demangler",
    "itsdangerous",
    "jaraco.classes",
    "jaraco.context",
    "jaraco.functools",
    "jedi",
    "jsonpath-ng",
    "jsonschema-specifications",
    "jupyter-client",
    "jupyter-core",
    "jupyterlab-pygments",
    "kaitaistruct",
    "keras",
    "kiwisolver",
    "ldap3",
    "libarchive-c",
    "libclang",
    "linkify-it-py",
    "llama-cpp-python",
    "llvmlite",
    "locket",
    "loguru",
    "lxml",
    "mako",
    "markdown",
    "markupsafe",
    "mccabe",
    "mdit-py-plugins",
    "mdurl",
    "mistune",
    "mitmproxy-rs",
    "more-itertools",
    "mpmath",
    "msgpack",
    "mss",
    "mulpyplexer",
    "multidict",
    "multiprocess",
    "mypy-extensions",
    "namex",
    "nampa",
    "nanobind",
    "nbclient",
    "nbconvert",
    "nbformat",
    "nh3",
    "nodeenv",
    "numba",
    "oauthlib",
    "oci",
    "opencensus",
    "opencensus-context",
    "opencv-python",
    "opentelemetry-api",
    "opentelemetry-exporter-prometheus",
    "opentelemetry-proto",
    "opentelemetry-sdk",
    "opentelemetry-semantic-conventions",
    "opt-einsum",
    "optree",
    "orjson",
    "overrides",
    "packaging",
    "pandocfilters",
    "panel",
    "param",
    "parso",
    "partd",
    "passlib",
    "pathspec",
    "pbr",
    "pickleshare",
    "pipdeptree",
    "pipreqs",
    "platformdirs",
    "pluggy",
    "plumbum",
    "pre-commit",
    "prometheus-client",
    "prompt-toolkit",
    "propcache",
    "proto-plus",
    "publicsuffix2",
    "pure-eval",
    "pwntools",
    "py-cpuinfo",
    "py-spy",
    "pyarrow",
    "pyasn1",
    "pyasn1-modules",
    "pycodestyle",
    "pydantic-settings",
    "pydivert",
    "pydot",
    "pydyf",
    "pyfiglet",
    "pyformlang",
    "pygetwindow",
    "pygit2",
    "pylint",
    "pylsqpack",
    "pymem",
    "pynacl",
    "pyparsing",
    "pyperclip",
    "pyphen",
    "pyproject-hooks",
    "pyqt6-qt6",
    "pyreadline3",
    "pyrect",
    "pyserial",
    "pysmt",
    "pysocks",
    "pyspnego",
    "pytest-asyncio",
    "pytest-xdist",
    "python-dateutil",
    "python-multipart",
    "python-registry",
    "pytools",
    "pytorch-triton-xpu",
    "pytz",
    "pyu2f",
    "pyvex",
    "pyviz-comms",
    "pywin32",
    "pywin32-ctypes",
    "pyzmq",
    "questionary",
    "readme-renderer",
    "referencing",
    "requests-oauthlib",
    "requests-toolbelt",
    "requests-viewer",
    "rfc3986",
    "rich-toolkit",
    "roman-numerals-py",
    "ropgadget",
    "rpds-py",
    "rpyc",
    "rsa",
    "ruamel.yaml",
    "ruamel.yaml.clib",
    "s3fs",
    "s3transfer",
    "service-identity",
    "shellingham",
    "siphash24",
    "six",
    "smart-open",
    "smbprotocol",
    "smmap",
    "sniffio",
    "snowballstemmer",
    "sortedcontainers",
    "soupsieve",
    "sphinx-basic-ng",
    "sphinxcontrib-applehelp",
    "sphinxcontrib-devhelp",
    "sphinxcontrib-htmlhelp",
    "sphinxcontrib-jquery",
    "sphinxcontrib-jsmath",
    "sphinxcontrib-qthelp",
    "sphinxcontrib-serializinghtml",
    "sspilib",
    "stack-data",
    "starlette",
    "stevedore",
    "stone",
    "sympy",
    "tblib",
    "tensorboard-data-server",
    "tensorflow-intel",
    "termcolor",
    "threadpoolctl",
    "tinyhtml5",
    "tokenizers",
    "tomlkit",
    "toolz",
    "tornado",
    "traitlets",
    "twine",
    "typer",
    "typer-slim",
    "typing-extensions",
    "typing-inspection",
    "tzdata",
    "uc-micro-py",
    "ujson",
    "unicodecsv",
    "unicorn",
    "unique-log-filter",
    "unix-ar",
    "urwid",
    "uv",
    "vine",
    "virtualenv",
    "vulture",
    "watchfiles",
    "wcwidth",
    "webencodings",
    "websockets",
    "werkzeug",
    "win-inet-pton",
    "win32-setctime",
    "windows-curses",
    "wrapt",
    "wsproto",
    "xxhash",
    "yamale",
    "yarg",
    "yarl",
    "zict",
    "zipp",
    "zope.event",
    "zope.interface",
    "zopfli",
    "zstandard",
]

for pkg_name in pip_packages:
    if pkg_name not in pyproject_packages:
        if pkg_name in critical:
            critical_packages.append((pkg_name, pip_packages[pkg_name]))
        else:
            missing_in_pyproject.append((pkg_name, pip_packages[pkg_name]))

print("=" * 60)
print("CRITICAL PACKAGES MISSING FROM PYPROJECT.TOML:")
print("=" * 60)
for pkg, version in sorted(critical_packages):
    print(f'    "{pkg}=={version}",')

print("\n" + "=" * 60)
print("OTHER PACKAGES MISSING FROM PYPROJECT.TOML:")
print("=" * 60)
for pkg, version in sorted(missing_in_pyproject):
    print(f'    "{pkg}=={version}",')

print(f"\nTotal missing critical: {len(critical_packages)}")
print(f"Total missing other: {len(missing_in_pyproject)}")
print(f"Total in pip: {len(pip_packages)}")
print(f"Total in pyproject: {len(pyproject_packages)}")
