// @ts-check

import pluginToml from 'eslint-plugin-toml';
import pluginYml from 'eslint-plugin-yml';
import pluginSecurity from 'eslint-plugin-security';
import pluginUnicorn from 'eslint-plugin-unicorn';
import pluginJsdoc from 'eslint-plugin-jsdoc';

const sharedIgnores = [
    'docs/**',
    'node_modules/**',
    'build/**',
    'dist/**',
    '.venv*/**',
    '.pixi/**',
    'tools/**',
    '*.min.js',
    '.github/**',
];

const fridaGlobals = {
    Java: 'readonly',
    ObjC: 'readonly',
    Module: 'readonly',
    Memory: 'readonly',
    Process: 'readonly',
    Thread: 'readonly',
    Interceptor: 'readonly',
    NativePointer: 'readonly',
    NativeFunction: 'readonly',
    NativeCallback: 'readonly',
    ptr: 'readonly',
    NULL: 'readonly',
    recv: 'readonly',
    send: 'readonly',
    rpc: 'readonly',
    Stalker: 'readonly',
    DebugSymbol: 'readonly',
    Instruction: 'readonly',
    ApiResolver: 'readonly',
    SocketListener: 'readonly',
    Socket: 'readonly',
    Stream: 'readonly',
    File: 'readonly',
    SqliteDatabase: 'readonly',
    hexdump: 'readonly',
    int64: 'readonly',
    uint64: 'readonly',
    Cloak: 'readonly',
    Kernel: 'readonly',
    Script: 'readonly',
    WeakRef: 'readonly',
    CModule: 'readonly',
    SystemFunction: 'readonly',
    ObjCClass: 'readonly',
    X86Writer: 'readonly',
    X86Relocator: 'readonly',
    Arm64Writer: 'readonly',
    Arm64Relocator: 'readonly',
    ArmWriter: 'readonly',
    ArmRelocator: 'readonly',
    ThumbWriter: 'readonly',
    ThumbRelocator: 'readonly',
    MipsWriter: 'readonly',
    MipsRelocator: 'readonly',
    UnixInputStream: 'readonly',
    UnixOutputStream: 'readonly',
    Win32InputStream: 'readonly',
    Win32OutputStream: 'readonly',
    IOStream: 'readonly',
    InputStream: 'readonly',
    OutputStream: 'readonly',
    ModuleMap: 'readonly',
    SourceMap: 'readonly',
    Checksum: 'readonly',
    MessageDispatcher: 'readonly',
    Frida: 'readonly',
};

const nodeGlobals = {
    console: 'readonly',
    process: 'readonly',
    Buffer: 'readonly',
    global: 'readonly',
    setTimeout: 'readonly',
    setInterval: 'readonly',
    clearTimeout: 'readonly',
    clearInterval: 'readonly',
    setImmediate: 'readonly',
    clearImmediate: 'readonly',
    __dirname: 'readonly',
    __filename: 'readonly',
    module: 'readonly',
    require: 'readonly',
    exports: 'writable',
    crypto: 'readonly',
    performance: 'readonly',
    TextDecoder: 'readonly',
    TextEncoder: 'readonly',
    Uint8Array: 'readonly',
    ArrayBuffer: 'readonly',
    DataView: 'readonly',
    BigInt: 'readonly',
    BigInt64Array: 'readonly',
    BigUint64Array: 'readonly',
    atob: 'readonly',
    btoa: 'readonly',
    globalThis: 'readonly',
};

export default [
    {
        files: ['**/*.js'],
        ignores: sharedIgnores,
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                ...nodeGlobals,
                ...fridaGlobals,
            },
        },
        plugins: {
            security: pluginSecurity,
            unicorn: pluginUnicorn,
            jsdoc: pluginJsdoc,
        },
        rules: {
            'no-unused-vars': [
                'error',
                {
                    args: 'all',
                    argsIgnorePattern: '^_',
                    caughtErrors: 'all',
                    caughtErrorsIgnorePattern: '^_',
                    destructuredArrayIgnorePattern: '^_',
                    varsIgnorePattern: '^_',
                },
            ],
            'no-undef': 'error',
            'no-unreachable': 'error',
            'no-constant-condition': 'error',
            'no-duplicate-case': 'error',
            'no-empty': ['error', { allowEmptyCatch: false }],
            'no-extra-semi': 'error',
            'no-func-assign': 'error',
            'no-invalid-regexp': 'error',
            'no-irregular-whitespace': 'error',
            'no-obj-calls': 'error',
            'no-sparse-arrays': 'error',
            'no-unexpected-multiline': 'error',
            'use-isnan': 'error',
            'valid-typeof': ['error', { requireStringLiterals: true }],
            'no-fallthrough': 'error',
            'no-octal': 'error',
            'no-redeclare': 'error',
            'no-self-assign': ['error', { props: true }],
            'no-unused-labels': 'error',
            'no-useless-escape': 'error',
            'no-delete-var': 'error',
            'no-shadow-restricted-names': 'error',
            'constructor-super': 'error',
            'no-class-assign': 'error',
            'no-const-assign': 'error',
            'no-dupe-class-members': 'error',
            'no-new-symbol': 'error',
            'no-this-before-super': 'error',
            'require-yield': 'error',
            'no-cond-assign': ['error', 'always'],
            'no-dupe-args': 'error',
            'no-dupe-keys': 'error',
            'no-duplicate-imports': 'error',
            'no-empty-pattern': 'error',
            'no-ex-assign': 'error',
            'no-extra-boolean-cast': 'error',
            'no-inner-declarations': 'error',
            'no-prototype-builtins': 'error',
            'no-template-curly-in-string': 'error',
            'no-unsafe-finally': 'error',
            'no-unsafe-negation': 'error',
            'require-atomic-updates': 'error',
            'array-callback-return': 'error',
            'block-scoped-var': 'error',
            'class-methods-use-this': 'off',
            complexity: 'off',
            'consistent-return': 'error',
            'default-case': 'error',
            'default-case-last': 'error',
            'default-param-last': 'error',
            'dot-notation': 'error',
            'grouped-accessor-pairs': 'error',
            'guard-for-in': 'error',
            'max-classes-per-file': ['error', 5],
            'no-alert': 'error',
            'no-caller': 'error',
            'no-case-declarations': 'error',
            'no-constructor-return': 'error',
            'no-div-regex': 'error',
            'no-else-return': 'error',
            'no-empty-function': ['error', { allow: ['arrowFunctions', 'methods'] }],
            'no-eq-null': 'off',
            'no-eval': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-extra-label': 'error',
            'no-floating-decimal': 'error',
            'no-global-assign': 'error',
            'no-implicit-coercion': 'error',
            'no-implicit-globals': 'error',
            'no-implied-eval': 'error',
            'no-invalid-this': 'off',
            'no-iterator': 'error',
            'no-labels': 'error',
            'no-lone-blocks': 'error',
            'no-loop-func': 'error',
            'no-magic-numbers': 'off',
            'no-multi-str': 'error',
            'no-new': 'error',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-nonoctal-decimal-escape': 'error',
            'no-octal-escape': 'error',
            'no-param-reassign': 'off',
            'no-proto': 'error',
            'no-return-assign': 'error',
            'no-return-await': 'error',
            'no-script-url': 'error',
            'no-self-compare': 'error',
            'no-sequences': 'error',
            'no-throw-literal': 'error',
            'no-unmodified-loop-condition': 'error',
            'no-unused-expressions': 'error',
            'no-useless-call': 'error',
            'no-useless-catch': 'error',
            'no-useless-concat': 'error',
            'no-useless-return': 'error',
            'no-void': 'error',
            'no-warning-comments': 'off',
            'no-with': 'error',
            'prefer-named-capture-group': 'off',
            'prefer-promise-reject-errors': 'error',
            'prefer-regex-literals': 'error',
            radix: 'error',
            'require-await': 'error',
            'require-unicode-regexp': 'off',
            'vars-on-top': 'error',
            yoda: 'error',
            'no-label-var': 'error',
            'no-shadow': 'off',
            'no-undef-init': 'error',
            'no-undefined': 'off',
            'no-use-before-define': ['error', { functions: false, classes: true, variables: true }],
            'arrow-body-style': ['error', 'as-needed'],
            'arrow-parens': ['error', 'as-needed'],
            'arrow-spacing': 'error',
            'generator-star-spacing': ['error', { before: false, after: true }],
            'no-confusing-arrow': 'error',
            'no-duplicate-imports': 'error',
            'no-useless-computed-key': 'error',
            'no-useless-constructor': 'error',
            'no-useless-rename': 'error',
            'no-var': 'error',
            'object-shorthand': ['error', 'always'],
            'prefer-arrow-callback': 'error',
            'prefer-const': 'error',
            'prefer-destructuring': [
                'error',
                {
                    array: false,
                    object: true,
                },
            ],
            'prefer-numeric-literals': 'error',
            'prefer-rest-params': 'error',
            'prefer-spread': 'error',
            'prefer-template': 'error',
            'rest-spread-spacing': ['error', 'never'],
            'symbol-description': 'error',
            'template-curly-spacing': 'error',
            'yield-star-spacing': ['error', 'after'],
            semi: ['error', 'always'],
            quotes: ['error', 'single', { avoidEscape: true, allowTemplateLiterals: true }],
            indent: ['error', 4, { SwitchCase: 1 }],
            'no-trailing-spaces': 'error',
            'eol-last': 'error',
            'comma-dangle': ['error', 'only-multiline'],
            'no-multi-spaces': 'error',
            'space-before-blocks': 'error',
            'keyword-spacing': 'error',
            'space-infix-ops': 'error',
            eqeqeq: ['error', 'always', { null: 'ignore' }],
            curly: ['error', 'all'],
            'brace-style': ['error', '1tbs', { allowSingleLine: true }],
            'no-console': 'off',
            camelcase: ['error', { properties: 'never', ignoreDestructuring: true }],
            'comma-spacing': ['error', { before: false, after: true }],
            'comma-style': ['error', 'last'],
            'computed-property-spacing': ['error', 'never'],
            'func-call-spacing': ['error', 'never'],
            'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
            'key-spacing': ['error', { beforeColon: false, afterColon: true }],
            'linebreak-style': 'off',
            'lines-between-class-members': ['error', 'always'],
            'max-depth': 'off',
            'max-len': [
                'warn',
                {
                    code: 120,
                    ignoreStrings: true,
                    ignoreTemplateLiterals: true,
                    ignoreComments: true,
                },
            ],
            'max-lines': 'off',
            'max-lines-per-function': 'off',
            'max-nested-callbacks': ['error', 4],
            'max-params': ['warn', 6],
            'max-statements-per-line': ['error', { max: 1 }],
            'new-cap': ['error', { newIsCap: true, capIsNew: false }],
            'new-parens': 'error',
            'no-array-constructor': 'error',
            'no-bitwise': 'off',
            'no-continue': 'off',
            'no-lonely-if': 'error',
            'no-mixed-operators': 'error',
            'no-multiple-empty-lines': ['error', { max: 2, maxEOF: 1 }],
            'no-negated-condition': 'error',
            'no-nested-ternary': 'error',
            'no-new-object': 'error',
            'no-plusplus': 'off',
            'no-tabs': 'error',
            'no-underscore-dangle': 'off',
            'no-unneeded-ternary': 'error',
            'no-whitespace-before-property': 'error',
            'object-curly-newline': ['error', { consistent: true }],
            'object-curly-spacing': ['error', 'always'],
            'one-var': ['error', 'never'],
            'operator-assignment': ['error', 'always'],
            'operator-linebreak': ['error', 'before'],
            'padded-blocks': ['error', 'never'],
            'prefer-exponentiation-operator': 'error',
            'prefer-object-spread': 'error',
            'quote-props': ['error', 'as-needed'],
            'semi-spacing': ['error', { before: false, after: true }],
            'semi-style': ['error', 'last'],
            'space-before-function-paren': [
                'error',
                {
                    anonymous: 'always',
                    named: 'never',
                    asyncArrow: 'always',
                },
            ],
            'space-in-parens': ['error', 'never'],
            'space-unary-ops': 'error',
            'spaced-comment': ['error', 'always'],
            'switch-colon-spacing': ['error', { after: true, before: false }],
            'template-tag-spacing': ['error', 'never'],
            'unicode-bom': ['error', 'never'],
            'wrap-regex': 'off',
            'security/detect-object-injection': 'off',
            'security/detect-non-literal-fs-filename': 'off',
            'security/detect-non-literal-regexp': 'off',
            'security/detect-unsafe-regex': 'error',
            'security/detect-buffer-noassert': 'error',
            'security/detect-child-process': 'off',
            'security/detect-disable-mustache-escape': 'error',
            'security/detect-eval-with-expression': 'error',
            'security/detect-new-buffer': 'error',
            'security/detect-no-csrf-before-method-override': 'error',
            'security/detect-possible-timing-attacks': 'warn',
            'security/detect-pseudoRandomBytes': 'error',
            'security/detect-bidi-characters': 'error',
            'unicorn/better-regex': 'error',
            'unicorn/catch-error-name': ['error', { name: 'error' }],
            'unicorn/consistent-destructuring': 'error',
            'unicorn/consistent-function-scoping': 'error',
            'unicorn/custom-error-definition': 'error',
            'unicorn/empty-brace-spaces': 'error',
            'unicorn/error-message': 'error',
            'unicorn/escape-case': 'error',
            'unicorn/expiring-todo-comments': 'warn',
            'unicorn/explicit-length-check': 'error',
            'unicorn/import-style': 'off',
            'unicorn/new-for-builtins': 'error',
            'unicorn/no-abusive-eslint-disable': 'error',
            'unicorn/no-array-callback-reference': 'off',
            'unicorn/no-array-for-each': 'off',
            'unicorn/no-array-method-this-argument': 'error',
            'unicorn/no-array-push-push': 'error',
            'unicorn/no-array-reduce': 'off',
            'unicorn/no-await-expression-member': 'error',
            'unicorn/no-console-spaces': 'error',
            'unicorn/no-document-cookie': 'error',
            'unicorn/no-empty-file': 'error',
            'unicorn/no-for-loop': 'error',
            'unicorn/no-hex-escape': 'error',
            'unicorn/no-instanceof-array': 'error',
            'unicorn/no-invalid-remove-event-listener': 'error',
            'unicorn/no-keyword-prefix': 'off',
            'unicorn/no-lonely-if': 'error',
            'unicorn/no-negated-condition': 'error',
            'unicorn/no-nested-ternary': 'error',
            'unicorn/no-new-array': 'error',
            'unicorn/no-new-buffer': 'error',
            'unicorn/no-null': 'off',
            'unicorn/no-object-as-default-parameter': 'error',
            'unicorn/no-process-exit': 'off',
            'unicorn/no-static-only-class': 'error',
            'unicorn/no-thenable': 'error',
            'unicorn/no-this-assignment': 'error',
            'unicorn/no-typeof-undefined': 'error',
            'unicorn/no-unnecessary-await': 'error',
            'unicorn/no-unnecessary-polyfills': 'off',
            'unicorn/no-unreadable-array-destructuring': 'error',
            'unicorn/no-unreadable-iife': 'error',
            'unicorn/no-unused-properties': 'warn',
            'unicorn/no-useless-fallback-in-spread': 'error',
            'unicorn/no-useless-length-check': 'error',
            'unicorn/no-useless-promise-resolve-reject': 'error',
            'unicorn/no-useless-spread': 'error',
            'unicorn/no-useless-switch-case': 'error',
            'unicorn/no-useless-undefined': 'off',
            'unicorn/no-zero-fractions': 'error',
            'unicorn/number-literal-case': 'error',
            'unicorn/numeric-separators-style': 'error',
            'unicorn/prefer-add-event-listener': 'error',
            'unicorn/prefer-array-find': 'error',
            'unicorn/prefer-array-flat': 'error',
            'unicorn/prefer-array-flat-map': 'error',
            'unicorn/prefer-array-index-of': 'error',
            'unicorn/prefer-array-some': 'error',
            'unicorn/prefer-at': 'error',
            'unicorn/prefer-blob-reading-methods': 'error',
            'unicorn/prefer-code-point': 'error',
            'unicorn/prefer-date-now': 'error',
            'unicorn/prefer-default-parameters': 'error',
            'unicorn/prefer-dom-node-append': 'error',
            'unicorn/prefer-dom-node-dataset': 'error',
            'unicorn/prefer-dom-node-remove': 'error',
            'unicorn/prefer-dom-node-text-content': 'error',
            'unicorn/prefer-event-target': 'error',
            'unicorn/prefer-export-from': 'error',
            'unicorn/prefer-includes': 'error',
            'unicorn/prefer-json-parse-buffer': 'off',
            'unicorn/prefer-keyboard-event-key': 'error',
            'unicorn/prefer-logical-operator-over-ternary': 'error',
            'unicorn/prefer-math-trunc': 'error',
            'unicorn/prefer-modern-dom-apis': 'error',
            'unicorn/prefer-modern-math-apis': 'error',
            'unicorn/prefer-module': 'off',
            'unicorn/prefer-native-coercion-functions': 'error',
            'unicorn/prefer-negative-index': 'error',
            'unicorn/prefer-node-protocol': 'off',
            'unicorn/prefer-number-properties': 'error',
            'unicorn/prefer-object-from-entries': 'error',
            'unicorn/prefer-optional-catch-binding': 'error',
            'unicorn/prefer-prototype-methods': 'error',
            'unicorn/prefer-query-selector': 'error',
            'unicorn/prefer-reflect-apply': 'error',
            'unicorn/prefer-regexp-test': 'error',
            'unicorn/prefer-set-has': 'error',
            'unicorn/prefer-set-size': 'error',
            'unicorn/prefer-spread': 'error',
            'unicorn/prefer-string-replace-all': 'error',
            'unicorn/prefer-string-slice': 'error',
            'unicorn/prefer-string-starts-ends-with': 'error',
            'unicorn/prefer-string-trim-start-end': 'error',
            'unicorn/prefer-switch': 'error',
            'unicorn/prefer-ternary': 'off',
            'unicorn/prefer-top-level-await': 'off',
            'unicorn/prefer-type-error': 'error',
            'unicorn/prevent-abbreviations': 'off',
            'unicorn/relative-url-style': 'error',
            'unicorn/require-array-join-separator': 'error',
            'unicorn/require-number-to-fixed-digits-argument': 'error',
            'unicorn/require-post-message-target-origin': 'off',
            'unicorn/string-content': 'off',
            'unicorn/switch-case-braces': 'error',
            'unicorn/template-indent': 'error',
            'unicorn/text-encoding-identifier-case': 'error',
            'unicorn/throw-new-error': 'error',
            'jsdoc/check-access': 'error',
            'jsdoc/check-alignment': 'error',
            'jsdoc/check-examples': 'off',
            'jsdoc/check-indentation': 'warn',
            'jsdoc/check-line-alignment': 'warn',
            'jsdoc/check-param-names': 'error',
            'jsdoc/check-property-names': 'error',
            'jsdoc/check-syntax': 'error',
            'jsdoc/check-tag-names': 'error',
            'jsdoc/check-types': 'error',
            'jsdoc/check-values': 'error',
            'jsdoc/empty-tags': 'error',
            'jsdoc/implements-on-classes': 'error',
            'jsdoc/match-description': 'off',
            'jsdoc/multiline-blocks': 'error',
            'jsdoc/no-bad-blocks': 'error',
            'jsdoc/no-blank-block-descriptions': 'error',
            'jsdoc/no-defaults': 'error',
            'jsdoc/no-missing-syntax': 'off',
            'jsdoc/no-multi-asterisks': 'error',
            'jsdoc/no-restricted-syntax': 'off',
            'jsdoc/no-types': 'off',
            'jsdoc/no-undefined-types': 'off',
            'jsdoc/require-asterisk-prefix': 'error',
            'jsdoc/require-description': 'off',
            'jsdoc/require-description-complete-sentence': 'off',
            'jsdoc/require-example': 'off',
            'jsdoc/require-file-overview': 'off',
            'jsdoc/require-hyphen-before-param-description': ['error', 'never'],
            'jsdoc/require-jsdoc': 'off',
            'jsdoc/require-param': 'off',
            'jsdoc/require-param-description': 'off',
            'jsdoc/require-param-name': 'error',
            'jsdoc/require-param-type': 'off',
            'jsdoc/require-property': 'off',
            'jsdoc/require-property-description': 'off',
            'jsdoc/require-property-name': 'error',
            'jsdoc/require-property-type': 'off',
            'jsdoc/require-returns': 'off',
            'jsdoc/require-returns-check': 'error',
            'jsdoc/require-returns-description': 'off',
            'jsdoc/require-returns-type': 'off',
            'jsdoc/require-throws': 'off',
            'jsdoc/require-yields': 'off',
            'jsdoc/require-yields-check': 'error',
            'jsdoc/sort-tags': 'off',
            'jsdoc/tag-lines': ['error', 'any', { startLines: 1 }],
            'jsdoc/valid-types': 'error',
        },
    },
    ...pluginToml.configs['flat/recommended'],
    {
        files: ['**/*.toml'],
        ignores: [
            'node_modules/**',
            '.pixi/**',
            '.venv*/**',
            'tools/**',
            'build/**',
            'dist/**',
            'scripts/scanner/.cargo/**',
        ],
        rules: {
            'toml/indent': ['error', 2],
            'toml/array-bracket-newline': 'error',
            'toml/array-bracket-spacing': 'error',
            'toml/array-element-newline': 'error',
            'toml/comma-style': 'error',
            'toml/inline-table-curly-spacing': 'error',
            'toml/key-spacing': 'error',
            'toml/keys-order': 'error',
            'toml/no-space-dots': 'error',
            'toml/no-unreadable-number-separator': 'error',
            'toml/padding-line-between-pairs': 'error',
            'toml/padding-line-between-tables': 'error',
            'toml/precision-of-fractional-seconds': 'error',
            'toml/precision-of-integer': 'error',
            'toml/quoted-keys': 'error',
            'toml/spaced-comment': 'error',
            'toml/table-bracket-spacing': 'error',
            'toml/tables-order': 'error',
        },
    },
    ...pluginYml.configs['flat/recommended'],
    {
        files: ['**/*.yaml', '**/*.yml'],
        ignores: [
            'node_modules/**',
            '.pixi/**',
            '.venv*/**',
            'tools/**',
            'build/**',
            'dist/**',
            '.github/**',
        ],
        rules: {
            'yml/indent': ['error', 2],
            'yml/no-empty-document': 'error',
            'yml/no-empty-key': 'error',
            'yml/no-empty-mapping-value': 'error',
            'yml/no-empty-sequence-entry': 'error',
            'yml/no-irregular-whitespace': 'error',
            'yml/no-tab-indent': 'error',
            'yml/plain-scalar': 'error',
            'yml/quotes': ['error', { prefer: 'single', avoidEscape: true }],
            'yml/spaced-comment': 'error',
            'yml/block-mapping-question-indicator-newline': 'error',
            'yml/block-sequence-hyphen-indicator-newline': 'error',
            'yml/flow-mapping-curly-newline': 'error',
            'yml/flow-mapping-curly-spacing': 'error',
            'yml/flow-sequence-bracket-newline': 'error',
            'yml/flow-sequence-bracket-spacing': 'error',
            'yml/key-spacing': 'error',
            'yml/no-multiple-empty-lines': 'error',
            'yml/sort-keys': 'off',
            'yml/sort-sequence-values': 'off',
        },
    },
];
