"""PyQt6.QtCore type definitions for strict mypy compliance."""

from typing import Any, Callable


class QObject:
    """Base Qt object class with proper typing."""

    def __init__(self, parent: QObject | None = None) -> None: ...
    def objectName(self) -> str: ...
    def setObjectName(self, name: str) -> None: ...
    def parent(self) -> QObject | None: ...
    def setParent(self, parent: QObject | None) -> None: ...
    def children(self) -> list[QObject]: ...
    def findChild(self, type: type, name: str = "") -> Any: ...
    def findChildren(self, type: type, name: str = "") -> list[Any]: ...
    def deleteLater(self) -> None: ...
    def blockSignals(self, block: bool) -> bool: ...
    def signalsBlocked(self) -> bool: ...
    def property(self, name: str) -> Any: ...
    def setProperty(self, name: str, value: Any) -> bool: ...


class QThread(QObject):
    """Thread class with proper typing."""

    started: Any
    finished: Any

    def __init__(self, parent: QObject | None = None) -> None: ...
    def run(self) -> None: ...
    def start(self, priority: int = ...) -> None: ...
    def terminate(self) -> None: ...
    def quit(self) -> None: ...
    def wait(self, time: int = ...) -> bool: ...
    def isRunning(self) -> bool: ...
    def isFinished(self) -> bool: ...
    def requestInterruption(self) -> None: ...
    def isInterruptionRequested(self) -> bool: ...
    @staticmethod
    def currentThread() -> QThread: ...
    @staticmethod
    def msleep(msecs: int) -> None: ...
    @staticmethod
    def sleep(secs: int) -> None: ...
    @staticmethod
    def usleep(usecs: int) -> None: ...


class QTimer(QObject):
    """Timer class with proper typing."""

    timeout: Any

    def __init__(self, parent: QObject | None = None) -> None: ...
    def start(self, msec: int = ...) -> None: ...
    def stop(self) -> None: ...
    def isActive(self) -> bool: ...
    def setInterval(self, msec: int) -> None: ...
    def interval(self) -> int: ...
    def setSingleShot(self, singleShot: bool) -> None: ...
    def isSingleShot(self) -> bool: ...
    def remainingTime(self) -> int: ...
    @staticmethod
    def singleShot(msec: int, receiver: Callable[[], None]) -> None: ...


class pyqtSignal:
    """Signal class with proper typing."""

    def __init__(self, *types: type) -> None: ...
    def emit(self, *args: Any) -> None: ...
    def connect(self, slot: Callable[..., Any]) -> None: ...
    def disconnect(self, slot: Callable[..., Any] | None = None) -> None: ...


class pyqtSlot:
    """Slot decorator with proper typing."""

    def __init__(self, *types: type, result: type | None = None) -> None: ...
    def __call__(self, func: Callable[..., Any]) -> Callable[..., Any]: ...


class Qt:
    """Qt namespace with constants."""

    # Alignment flags
    AlignLeft: int
    AlignRight: int
    AlignHCenter: int
    AlignTop: int
    AlignBottom: int
    AlignVCenter: int
    AlignCenter: int

    # Orientation
    Horizontal: int
    Vertical: int

    # Window types
    Widget: int
    Window: int
    Dialog: int
    Sheet: int
    Drawer: int
    Popup: int
    Tool: int
    ToolTip: int
    SplashScreen: int
    Desktop: int
    SubWindow: int
    WindowStaysOnTopHint: int
    WindowStaysOnBottomHint: int
    FramelessWindowHint: int
    CustomizeWindowHint: int
    WindowTitleHint: int
    WindowSystemMenuHint: int
    WindowMinimizeButtonHint: int
    WindowMaximizeButtonHint: int
    WindowMinMaxButtonsHint: int
    WindowCloseButtonHint: int

    # Item flags
    NoItemFlags: int
    ItemIsSelectable: int
    ItemIsEditable: int
    ItemIsDragEnabled: int
    ItemIsDropEnabled: int
    ItemIsUserCheckable: int
    ItemIsEnabled: int
    ItemIsAutoTristate: int
    ItemNeverHasChildren: int
    ItemIsUserTristate: int

    # Check state
    Unchecked: int
    PartiallyChecked: int
    Checked: int

    # Item data roles
    DisplayRole: int
    DecorationRole: int
    EditRole: int
    ToolTipRole: int
    StatusTipRole: int
    WhatsThisRole: int
    FontRole: int
    TextAlignmentRole: int
    BackgroundRole: int
    ForegroundRole: int
    CheckStateRole: int
    UserRole: int

    # Focus policies
    NoFocus: int
    TabFocus: int
    ClickFocus: int
    StrongFocus: int
    WheelFocus: int

    # Scroll bar policies
    ScrollBarAsNeeded: int
    ScrollBarAlwaysOff: int
    ScrollBarAlwaysOn: int

    # Context menu policies
    NoContextMenu: int
    DefaultContextMenu: int
    ActionsContextMenu: int
    CustomContextMenu: int
    PreventContextMenu: int

    # Cursor shapes
    ArrowCursor: int
    UpArrowCursor: int
    CrossCursor: int
    WaitCursor: int
    IBeamCursor: int
    SizeVerCursor: int
    SizeHorCursor: int
    SizeBDiagCursor: int
    SizeFDiagCursor: int
    SizeAllCursor: int
    BlankCursor: int
    SplitVCursor: int
    SplitHCursor: int
    PointingHandCursor: int
    ForbiddenCursor: int
    WhatsThisCursor: int
    BusyCursor: int
    OpenHandCursor: int
    ClosedHandCursor: int
    DragCopyCursor: int
    DragMoveCursor: int
    DragLinkCursor: int

    # Text flags
    TextSingleLine: int
    TextDontClip: int
    TextExpandTabs: int
    TextShowMnemonic: int
    TextWordWrap: int
    TextWrapAnywhere: int
    TextDontPrint: int
    TextIncludeTrailingSpaces: int
    TextHideMnemonic: int
    TextJustificationForced: int

    class Orientation:
        """Orientation enum."""

        Horizontal: int
        Vertical: int

    class ItemDataRole:
        """Item data role enum."""

        DisplayRole: int
        EditRole: int
        UserRole: int

    class AlignmentFlag:
        """Alignment flag enum."""

        AlignLeft: int
        AlignRight: int
        AlignCenter: int

    class TextInteractionFlag:
        """Text interaction flag enum."""

        NoTextInteraction: int
        TextSelectableByMouse: int
        TextSelectableByKeyboard: int
        LinksAccessibleByMouse: int
        LinksAccessibleByKeyboard: int
        TextEditable: int
        TextEditorInteraction: int
        TextBrowserInteraction: int

    class WindowModality:
        """Window modality enum."""

        NonModal: int
        WindowModal: int
        ApplicationModal: int

    # Text interaction flags
    NoTextInteraction: int
    TextSelectableByMouse: int
    TextSelectableByKeyboard: int
    LinksAccessibleByMouse: int
    LinksAccessibleByKeyboard: int
    TextEditable: int
    TextEditorInteraction: int
    TextBrowserInteraction: int

    # Window modality
    NonModal: int
    WindowModal: int
    ApplicationModal: int


class QSize:
    """Size class with proper typing."""

    def __init__(self, width: int = 0, height: int = 0) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def setWidth(self, width: int) -> None: ...
    def setHeight(self, height: int) -> None: ...
    def isValid(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def isNull(self) -> bool: ...
    def expandedTo(self, other: QSize) -> QSize: ...
    def boundedTo(self, other: QSize) -> QSize: ...
    def scale(self, *args: Any) -> None: ...
    def scaled(self, *args: Any) -> QSize: ...
    def transpose(self) -> None: ...
    def transposed(self) -> QSize: ...


class QPoint:
    """Point class with proper typing."""

    def __init__(self, x: int = 0, y: int = 0) -> None: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def setX(self, x: int) -> None: ...
    def setY(self, y: int) -> None: ...
    def isNull(self) -> bool: ...
    def manhattanLength(self) -> int: ...


class QRect:
    """Rectangle class with proper typing."""

    def __init__(self, *args: Any) -> None: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def setX(self, x: int) -> None: ...
    def setY(self, y: int) -> None: ...
    def setWidth(self, width: int) -> None: ...
    def setHeight(self, height: int) -> None: ...
    def left(self) -> int: ...
    def right(self) -> int: ...
    def top(self) -> int: ...
    def bottom(self) -> int: ...
    def topLeft(self) -> QPoint: ...
    def topRight(self) -> QPoint: ...
    def bottomLeft(self) -> QPoint: ...
    def bottomRight(self) -> QPoint: ...
    def center(self) -> QPoint: ...
    def size(self) -> QSize: ...
    def isValid(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def isNull(self) -> bool: ...
    def contains(self, *args: Any) -> bool: ...
    def intersects(self, rect: QRect) -> bool: ...


class QMargins:
    """Margins class with proper typing."""

    def __init__(self, left: int = 0, top: int = 0, right: int = 0, bottom: int = 0) -> None: ...
    def left(self) -> int: ...
    def top(self) -> int: ...
    def right(self) -> int: ...
    def bottom(self) -> int: ...
    def setLeft(self, left: int) -> None: ...
    def setTop(self, top: int) -> None: ...
    def setRight(self, right: int) -> None: ...
    def setBottom(self, bottom: int) -> None: ...
    def isNull(self) -> bool: ...


class QRegularExpression:
    """Regular expression class with proper typing."""

    class PatternOption:
        """Pattern option enum."""

        NoPatternOption: int
        CaseInsensitiveOption: int
        DotMatchesEverythingOption: int
        MultilineOption: int
        ExtendedPatternSyntaxOption: int
        InvertedGreedinessOption: int
        DontCaptureOption: int
        UseUnicodePropertiesOption: int

    NoPatternOption: int
    CaseInsensitiveOption: int
    DotMatchesEverythingOption: int
    MultilineOption: int

    def __init__(self, pattern: str = "", options: int = 0) -> None: ...
    def pattern(self) -> str: ...
    def setPattern(self, pattern: str) -> None: ...
    def patternOptions(self) -> int: ...
    def setPatternOptions(self, options: int) -> None: ...
    def isValid(self) -> bool: ...
    def errorString(self) -> str: ...
    def match(self, subject: str, offset: int = 0) -> Any: ...
    def globalMatch(self, subject: str, offset: int = 0) -> Any: ...


class QMutex:
    """Mutex class with proper typing."""

    def __init__(self) -> None: ...
    def lock(self) -> None: ...
    def unlock(self) -> None: ...
    def tryLock(self, timeout: int = 0) -> bool: ...


class QMutexLocker:
    """Mutex locker class with proper typing."""

    def __init__(self, mutex: QMutex) -> None: ...
    def unlock(self) -> None: ...
    def relock(self) -> None: ...


class QModelIndex:
    """Model index class with proper typing."""

    def __init__(self) -> None: ...
    def row(self) -> int: ...
    def column(self) -> int: ...
    def parent(self) -> QModelIndex: ...
    def sibling(self, row: int, column: int) -> QModelIndex: ...
    def data(self, role: int = ...) -> Any: ...
    def flags(self) -> int: ...
    def model(self) -> Any: ...
    def isValid(self) -> bool: ...
    def internalPointer(self) -> Any: ...


class QUrl:
    """URL class with proper typing."""

    def __init__(self, url: str = "") -> None: ...
    def toString(self) -> str: ...
    def toLocalFile(self) -> str: ...
    def isValid(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def scheme(self) -> str: ...
    def host(self) -> str: ...
    def port(self, defaultPort: int = -1) -> int: ...
    def path(self) -> str: ...
    def query(self) -> str: ...
    def fragment(self) -> str: ...
    def setScheme(self, scheme: str) -> None: ...
    def setHost(self, host: str) -> None: ...
    def setPort(self, port: int) -> None: ...
    def setPath(self, path: str) -> None: ...
    def setQuery(self, query: str) -> None: ...
    def setFragment(self, fragment: str) -> None: ...
    @staticmethod
    def fromLocalFile(localFile: str) -> QUrl: ...


class QDateTime:
    """DateTime class with proper typing."""

    def __init__(self) -> None: ...
    def toString(self, format: str = "") -> str: ...
    def toSecsSinceEpoch(self) -> int: ...
    def toMSecsSinceEpoch(self) -> int: ...
    def isValid(self) -> bool: ...
    def isNull(self) -> bool: ...
    @staticmethod
    def currentDateTime() -> QDateTime: ...
    @staticmethod
    def fromSecsSinceEpoch(secs: int) -> QDateTime: ...
    @staticmethod
    def fromMSecsSinceEpoch(msecs: int) -> QDateTime: ...


class QDate:
    """Date class with proper typing."""

    def __init__(self, year: int = 0, month: int = 0, day: int = 0) -> None: ...
    def year(self) -> int: ...
    def month(self) -> int: ...
    def day(self) -> int: ...
    def toString(self, format: str = "") -> str: ...
    def isValid(self) -> bool: ...
    def isNull(self) -> bool: ...
    @staticmethod
    def currentDate() -> QDate: ...


class QTime:
    """Time class with proper typing."""

    def __init__(self, hour: int = 0, minute: int = 0, second: int = 0, msec: int = 0) -> None: ...
    def hour(self) -> int: ...
    def minute(self) -> int: ...
    def second(self) -> int: ...
    def msec(self) -> int: ...
    def toString(self, format: str = "") -> str: ...
    def isValid(self) -> bool: ...
    def isNull(self) -> bool: ...
    @staticmethod
    def currentTime() -> QTime: ...


class QSettings:
    """Settings class with proper typing."""

    def __init__(self, *args: Any) -> None: ...
    def value(self, key: str, defaultValue: Any = None) -> Any: ...
    def setValue(self, key: str, value: Any) -> None: ...
    def contains(self, key: str) -> bool: ...
    def remove(self, key: str) -> None: ...
    def clear(self) -> None: ...
    def sync(self) -> None: ...
    def allKeys(self) -> list[str]: ...
    def childKeys(self) -> list[str]: ...
    def childGroups(self) -> list[str]: ...
    def beginGroup(self, prefix: str) -> None: ...
    def endGroup(self) -> None: ...
    def group(self) -> str: ...


class QByteArray:
    """Byte array class with proper typing."""

    def __init__(self, data: bytes | str = b"") -> None: ...
    def data(self) -> bytes: ...
    def size(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def isNull(self) -> bool: ...
    def clear(self) -> None: ...
    def append(self, data: bytes | str | QByteArray) -> QByteArray: ...
    def prepend(self, data: bytes | str | QByteArray) -> QByteArray: ...
    def insert(self, pos: int, data: bytes | str | QByteArray) -> QByteArray: ...
    def remove(self, pos: int, len: int) -> QByteArray: ...
    def replace(self, *args: Any) -> QByteArray: ...
    def toHex(self) -> QByteArray: ...
    @staticmethod
    def fromHex(hexEncoded: bytes | str | QByteArray) -> QByteArray: ...
