"""PyQt6.QtGui type definitions for strict mypy compliance."""

from typing import Any


class QColor:
    """Color class with proper typing."""

    def __init__(self, *args: Any) -> None: ...
    def red(self) -> int: ...
    def green(self) -> int: ...
    def blue(self) -> int: ...
    def alpha(self) -> int: ...
    def setRed(self, red: int) -> None: ...
    def setGreen(self, green: int) -> None: ...
    def setBlue(self, blue: int) -> None: ...
    def setAlpha(self, alpha: int) -> None: ...
    def name(self) -> str: ...
    def setNamedColor(self, name: str) -> None: ...
    def isValid(self) -> bool: ...
    def lighter(self, factor: int = 150) -> QColor: ...
    def darker(self, factor: int = 200) -> QColor: ...
    def rgb(self) -> int: ...
    def rgba(self) -> int: ...
    def hue(self) -> int: ...
    def saturation(self) -> int: ...
    def value(self) -> int: ...
    def lightness(self) -> int: ...


class QFont:
    """Font class with proper typing."""

    class Weight:
        """Font weight enum."""

        Thin: int
        ExtraLight: int
        Light: int
        Normal: int
        Medium: int
        DemiBold: int
        Bold: int
        ExtraBold: int
        Black: int

    Normal: int
    Bold: int
    Thin: int
    Light: int
    Medium: int
    DemiBold: int
    ExtraBold: int
    Black: int

    def __init__(self, family: str = "", pointSize: int = -1, weight: int = -1, italic: bool = False) -> None: ...
    def family(self) -> str: ...
    def setFamily(self, family: str) -> None: ...
    def pointSize(self) -> int: ...
    def setPointSize(self, size: int) -> None: ...
    def pixelSize(self) -> int: ...
    def setPixelSize(self, size: int) -> None: ...
    def weight(self) -> int: ...
    def setWeight(self, weight: int) -> None: ...
    def bold(self) -> bool: ...
    def setBold(self, enable: bool) -> None: ...
    def italic(self) -> bool: ...
    def setItalic(self, enable: bool) -> None: ...
    def underline(self) -> bool: ...
    def setUnderline(self, enable: bool) -> None: ...
    def strikeOut(self) -> bool: ...
    def setStrikeOut(self, enable: bool) -> None: ...


class QTextCharFormat:
    """Text character format with proper typing."""

    def __init__(self) -> None: ...
    def setForeground(self, brush: QColor | Any) -> None: ...
    def foreground(self) -> Any: ...
    def setBackground(self, brush: QColor | Any) -> None: ...
    def background(self) -> Any: ...
    def setFont(self, font: QFont) -> None: ...
    def font(self) -> QFont: ...
    def setFontWeight(self, weight: int) -> None: ...
    def fontWeight(self) -> int: ...
    def setFontItalic(self, italic: bool) -> None: ...
    def fontItalic(self) -> bool: ...
    def setFontUnderline(self, underline: bool) -> None: ...
    def fontUnderline(self) -> bool: ...
    def setFontStrikeOut(self, strikeOut: bool) -> None: ...
    def fontStrikeOut(self) -> bool: ...
    def setFontFamily(self, family: str) -> None: ...
    def fontFamily(self) -> str: ...
    def setFontPointSize(self, size: float) -> None: ...
    def fontPointSize(self) -> float: ...


class QTextDocument:
    """Text document class with proper typing."""

    def __init__(self, parent: Any | None = None) -> None: ...
    def toPlainText(self) -> str: ...
    def toHtml(self) -> str: ...
    def setPlainText(self, text: str) -> None: ...
    def setHtml(self, html: str) -> None: ...
    def isEmpty(self) -> bool: ...
    def characterCount(self) -> int: ...
    def lineCount(self) -> int: ...
    def blockCount(self) -> int: ...
    def clear(self) -> None: ...
    def undo(self) -> None: ...
    def redo(self) -> None: ...
    def isUndoAvailable(self) -> bool: ...
    def isRedoAvailable(self) -> bool: ...
    def setModified(self, modified: bool = True) -> None: ...
    def isModified(self) -> bool: ...
    def defaultFont(self) -> QFont: ...
    def setDefaultFont(self, font: QFont) -> None: ...


class QSyntaxHighlighter:
    """Syntax highlighter base class with proper typing."""

    def __init__(self, parent: QTextDocument | None = None) -> None: ...
    def document(self) -> QTextDocument | None: ...
    def setDocument(self, doc: QTextDocument | None) -> None: ...
    def rehighlight(self) -> None: ...
    def rehighlightBlock(self, block: Any) -> None: ...
    def highlightBlock(self, text: str) -> None: ...
    def setFormat(self, start: int, count: int, format: QTextCharFormat) -> None: ...
    def format(self, position: int) -> QTextCharFormat: ...
    def currentBlock(self) -> Any: ...
    def currentBlockState(self) -> int: ...
    def previousBlockState(self) -> int: ...
    def setCurrentBlockState(self, state: int) -> None: ...


class QIcon:
    """Icon class with proper typing."""

    def __init__(self, *args: Any) -> None: ...
    def isNull(self) -> bool: ...
    def addFile(self, fileName: str, size: Any = None, mode: int = 0, state: int = 0) -> None: ...
    def addPixmap(self, pixmap: Any, mode: int = 0, state: int = 0) -> None: ...
    def pixmap(self, *args: Any) -> Any: ...
    def availableSizes(self, mode: int = 0, state: int = 0) -> list[Any]: ...
    @staticmethod
    def fromTheme(name: str) -> QIcon: ...


class QPixmap:
    """Pixmap class with proper typing."""

    def __init__(self, *args: Any) -> None: ...
    def isNull(self) -> bool: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def size(self) -> Any: ...
    def scaled(self, *args: Any) -> QPixmap: ...
    def fill(self, color: QColor) -> None: ...
    def save(self, fileName: str, format: str = ..., quality: int = -1) -> bool: ...
    def load(self, fileName: str, format: str = ...) -> bool: ...
    @staticmethod
    def fromImage(image: Any) -> QPixmap: ...


class QImage:
    """Image class with proper typing."""

    def __init__(self, *args: Any) -> None: ...
    def isNull(self) -> bool: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def size(self) -> Any: ...
    def save(self, fileName: str, format: str = ..., quality: int = -1) -> bool: ...
    def load(self, fileName: str, format: str = ...) -> bool: ...
    def scaled(self, *args: Any) -> QImage: ...
    def pixel(self, x: int, y: int) -> int: ...
    def setPixel(self, x: int, y: int, color: int) -> None: ...


class QPainter:
    """Painter class with proper typing."""

    def __init__(self, device: Any = None) -> None: ...
    def begin(self, device: Any) -> bool: ...
    def end(self) -> bool: ...
    def drawText(self, *args: Any) -> None: ...
    def drawRect(self, *args: Any) -> None: ...
    def drawLine(self, *args: Any) -> None: ...
    def drawEllipse(self, *args: Any) -> None: ...
    def drawPixmap(self, *args: Any) -> None: ...
    def drawImage(self, *args: Any) -> None: ...
    def fillRect(self, *args: Any) -> None: ...
    def setPen(self, pen: Any) -> None: ...
    def pen(self) -> Any: ...
    def setBrush(self, brush: Any) -> None: ...
    def brush(self) -> Any: ...
    def setFont(self, font: QFont) -> None: ...
    def font(self) -> QFont: ...
    def save(self) -> None: ...
    def restore(self) -> None: ...
    def translate(self, *args: Any) -> None: ...
    def rotate(self, angle: float) -> None: ...
    def scale(self, sx: float, sy: float) -> None: ...
    def setClipRect(self, *args: Any) -> None: ...


class QPen:
    """Pen class with proper typing."""

    def __init__(self, *args: Any) -> None: ...
    def setColor(self, color: QColor) -> None: ...
    def color(self) -> QColor: ...
    def setWidth(self, width: int) -> None: ...
    def width(self) -> int: ...
    def setStyle(self, style: int) -> None: ...
    def style(self) -> int: ...


class QBrush:
    """Brush class with proper typing."""

    def __init__(self, *args: Any) -> None: ...
    def setColor(self, color: QColor) -> None: ...
    def color(self) -> QColor: ...
    def setStyle(self, style: int) -> None: ...
    def style(self) -> int: ...


class QPalette:
    """Palette class with proper typing."""

    Window: int
    WindowText: int
    Base: int
    AlternateBase: int
    ToolTipBase: int
    ToolTipText: int
    PlaceholderText: int
    Text: int
    Button: int
    ButtonText: int
    BrightText: int
    Light: int
    Midlight: int
    Dark: int
    Mid: int
    Shadow: int
    Highlight: int
    HighlightedText: int
    Link: int
    LinkVisited: int

    def __init__(self, *args: Any) -> None: ...
    def setColor(self, role: int, color: QColor) -> None: ...
    def color(self, role: int) -> QColor: ...
    def setBrush(self, role: int, brush: Any) -> None: ...
    def brush(self, role: int) -> Any: ...


class QCursor:
    """Cursor class with proper typing."""

    def __init__(self, shape: int = 0) -> None: ...
    def shape(self) -> int: ...
    def setShape(self, shape: int) -> None: ...
    @staticmethod
    def pos() -> Any: ...
    @staticmethod
    def setPos(x: int, y: int) -> None: ...


class QAction:
    """Action class with proper typing."""

    triggered: Any

    def __init__(self, *args: Any) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setIcon(self, icon: QIcon) -> None: ...
    def icon(self) -> QIcon: ...
    def setShortcut(self, shortcut: str) -> None: ...
    def shortcut(self) -> Any: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def isEnabled(self) -> bool: ...
    def setCheckable(self, checkable: bool) -> None: ...
    def isCheckable(self) -> bool: ...
    def setChecked(self, checked: bool) -> None: ...
    def isChecked(self) -> bool: ...
    def trigger(self) -> None: ...


class QKeySequence:
    """Key sequence class with proper typing."""

    def __init__(self, key: str | int = "") -> None: ...
    def toString(self) -> str: ...
    @staticmethod
    def fromString(str: str) -> QKeySequence: ...


class QClipboard:
    """Clipboard class with proper typing."""

    def text(self) -> str: ...
    def setText(self, text: str) -> None: ...
    def clear(self) -> None: ...
    def mimeData(self) -> Any: ...
    def setMimeData(self, data: Any) -> None: ...


class QFontMetrics:
    """Font metrics class with proper typing."""

    def __init__(self, font: QFont) -> None: ...
    def height(self) -> int: ...
    def width(self, text: str) -> int: ...
    def horizontalAdvance(self, text: str) -> int: ...
    def ascent(self) -> int: ...
    def descent(self) -> int: ...
    def leading(self) -> int: ...
    def averageCharWidth(self) -> int: ...
    def maxWidth(self) -> int: ...
    def boundingRect(self, text: str) -> Any: ...
