"""PyQt6.QtWidgets type definitions for strict mypy compliance."""

from typing import Any

from PyQt6.QtCore import QObject


class QWidget(QObject):
    """Base widget class with proper typing."""

    def __init__(self, parent: QWidget | None = None) -> None: ...
    def setMinimumWidth(self, minw: int) -> None: ...
    def minimumWidth(self) -> int: ...
    def setMaximumWidth(self, maxw: int) -> None: ...
    def maximumWidth(self) -> int: ...
    def setMinimumHeight(self, minh: int) -> None: ...
    def minimumHeight(self) -> int: ...
    def setMaximumHeight(self, maxh: int) -> None: ...
    def maximumHeight(self) -> int: ...
    def setLayout(self, layout: Any) -> None: ...
    def layout(self) -> Any: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def close(self) -> bool: ...
    def setWindowTitle(self, title: str) -> None: ...
    def resize(self, w: int, h: int) -> None: ...
    def setMinimumSize(self, w: int, h: int) -> None: ...
    def setMaximumSize(self, w: int, h: int) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def isEnabled(self) -> bool: ...
    def setVisible(self, visible: bool) -> None: ...
    def isVisible(self) -> bool: ...
    def update(self) -> None: ...
    def repaint(self) -> None: ...
    def setStyleSheet(self, styleSheet: str) -> None: ...
    def styleSheet(self) -> str: ...
    def setToolTip(self, tip: str) -> None: ...
    def toolTip(self) -> str: ...
    def setFocus(self) -> None: ...
    def hasFocus(self) -> bool: ...
    def parentWidget(self) -> QWidget | None: ...
    def window(self) -> QWidget: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def geometry(self) -> Any: ...
    def setGeometry(self, *args: Any) -> None: ...
    def sizeHint(self) -> Any: ...
    def minimumSizeHint(self) -> Any: ...
    def setSizePolicy(self, *args: Any) -> None: ...
    def sizePolicy(self) -> Any: ...
    def setContentsMargins(self, left: int, top: int, right: int, bottom: int) -> None: ...
    def contentsMargins(self) -> Any: ...
    def setFixedSize(self, w: int, h: int) -> None: ...
    def setFixedWidth(self, w: int) -> None: ...
    def setFixedHeight(self, h: int) -> None: ...


class QDialog(QWidget):
    """Dialog window with proper typing."""

    Accepted: int
    Rejected: int

    def __init__(self, parent: QWidget | None = None) -> None: ...
    def exec(self) -> int: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...
    def done(self, result: int) -> None: ...
    def result(self) -> int: ...
    def setModal(self, modal: bool) -> None: ...
    def isModal(self) -> bool: ...
    def open(self) -> None: ...


class QFrame(QWidget):
    """Frame widget with proper typing."""

    NoFrame: int
    Box: int
    Panel: int
    StyledPanel: int
    HLine: int
    VLine: int
    WinPanel: int
    Plain: int
    Raised: int
    Sunken: int

    class Shape:
        NoFrame: int
        Box: int
        Panel: int
        StyledPanel: int
        HLine: int
        VLine: int
        WinPanel: int

    class Shadow:
        Plain: int
        Raised: int
        Sunken: int

    def __init__(self, parent: QWidget | None = None) -> None: ...
    def setFrameShape(self, shape: int) -> None: ...
    def frameShape(self) -> int: ...
    def setFrameShadow(self, shadow: int) -> None: ...
    def frameShadow(self) -> int: ...
    def setFrameStyle(self, style: int) -> None: ...
    def frameStyle(self) -> int: ...
    def setLineWidth(self, width: int) -> None: ...
    def lineWidth(self) -> int: ...
    def setMidLineWidth(self, width: int) -> None: ...
    def midLineWidth(self) -> int: ...


class QMainWindow(QWidget):
    """Main window with proper typing."""

    def __init__(self, parent: QWidget | None = None) -> None: ...
    def setCentralWidget(self, widget: QWidget) -> None: ...
    def centralWidget(self) -> QWidget | None: ...
    def menuBar(self) -> Any: ...
    def setMenuBar(self, menuBar: Any) -> None: ...
    def statusBar(self) -> Any: ...
    def setStatusBar(self, statusBar: Any) -> None: ...
    def addToolBar(self, *args: Any) -> Any: ...
    def addDockWidget(self, *args: Any) -> None: ...


class QLabel(QWidget):
    """Label widget with proper typing."""

    def __init__(self, text: str = "", parent: QWidget | None = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setPixmap(self, pixmap: Any) -> None: ...
    def pixmap(self) -> Any: ...
    def setAlignment(self, alignment: Any) -> None: ...
    def alignment(self) -> Any: ...
    def setWordWrap(self, on: bool) -> None: ...
    def wordWrap(self) -> bool: ...
    def setTextFormat(self, format: Any) -> None: ...
    def textFormat(self) -> Any: ...
    def setOpenExternalLinks(self, open: bool) -> None: ...
    def openExternalLinks(self) -> bool: ...
    def setTextInteractionFlags(self, flags: Any) -> None: ...
    def textInteractionFlags(self) -> Any: ...
    def setScaledContents(self, scaled: bool) -> None: ...
    def hasScaledContents(self) -> bool: ...


class QLineEdit(QWidget):
    """Line edit widget with proper typing."""

    class EchoMode:
        Normal: int
        NoEcho: int
        Password: int
        PasswordEchoOnEdit: int

    Normal: int
    NoEcho: int
    Password: int
    PasswordEchoOnEdit: int

    textChanged: Any
    textEdited: Any
    returnPressed: Any

    def __init__(self, text: str = "", parent: QWidget | None = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setPlaceholderText(self, text: str) -> None: ...
    def placeholderText(self) -> str: ...
    def setReadOnly(self, readOnly: bool) -> None: ...
    def isReadOnly(self) -> bool: ...
    def setEchoMode(self, mode: int) -> None: ...
    def echoMode(self) -> int: ...
    def clear(self) -> None: ...
    def selectAll(self) -> None: ...
    def setMaxLength(self, length: int) -> None: ...
    def maxLength(self) -> int: ...


class QTextEdit(QWidget):
    """Text edit widget with proper typing."""

    textChanged: Any

    def __init__(self, text: str = "", parent: QWidget | None = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def toPlainText(self) -> str: ...
    def toHtml(self) -> str: ...
    def setPlainText(self, text: str) -> None: ...
    def setHtml(self, html: str) -> None: ...
    def setReadOnly(self, readOnly: bool) -> None: ...
    def isReadOnly(self) -> bool: ...
    def clear(self) -> None: ...
    def append(self, text: str) -> None: ...
    def document(self) -> Any: ...


class QPushButton(QWidget):
    """Push button widget with proper typing."""

    clicked: Any

    def __init__(self, text: str = "", parent: QWidget | None = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setIcon(self, icon: Any) -> None: ...
    def icon(self) -> Any: ...
    def setCheckable(self, checkable: bool) -> None: ...
    def isCheckable(self) -> bool: ...
    def setChecked(self, checked: bool) -> None: ...
    def isChecked(self) -> bool: ...
    def click(self) -> None: ...
    def setDefault(self, default: bool) -> None: ...
    def isDefault(self) -> bool: ...


class QCheckBox(QWidget):
    """Check box widget with proper typing."""

    stateChanged: Any

    def __init__(self, text: str = "", parent: QWidget | None = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setChecked(self, checked: bool) -> None: ...
    def isChecked(self) -> bool: ...
    def setTristate(self, tristate: bool) -> None: ...
    def isTristate(self) -> bool: ...
    def checkState(self) -> Any: ...
    def setCheckState(self, state: Any) -> None: ...


class QComboBox(QWidget):
    """Combo box widget with proper typing."""

    currentIndexChanged: Any
    currentTextChanged: Any

    def __init__(self, parent: QWidget | None = None) -> None: ...
    def addItem(self, text: str, userData: Any = None) -> None: ...
    def addItems(self, texts: list[str]) -> None: ...
    def insertItem(self, index: int, text: str, userData: Any = None) -> None: ...
    def removeItem(self, index: int) -> None: ...
    def clear(self) -> None: ...
    def currentIndex(self) -> int: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def currentText(self) -> str: ...
    def setCurrentText(self, text: str) -> None: ...
    def count(self) -> int: ...
    def itemText(self, index: int) -> str: ...
    def itemData(self, index: int) -> Any: ...
    def setItemText(self, index: int, text: str) -> None: ...
    def setItemData(self, index: int, data: Any) -> None: ...
    def findText(self, text: str) -> int: ...
    def setEditable(self, editable: bool) -> None: ...
    def isEditable(self) -> bool: ...


class QSpinBox(QWidget):
    """Spin box widget with proper typing."""

    valueChanged: Any

    def __init__(self, parent: QWidget | None = None) -> None: ...
    def setValue(self, value: int) -> None: ...
    def value(self) -> int: ...
    def setMinimum(self, min: int) -> None: ...
    def minimum(self) -> int: ...
    def setMaximum(self, max: int) -> None: ...
    def maximum(self) -> int: ...
    def setRange(self, min: int, max: int) -> None: ...
    def setSingleStep(self, step: int) -> None: ...
    def singleStep(self) -> int: ...
    def setPrefix(self, prefix: str) -> None: ...
    def prefix(self) -> str: ...
    def setSuffix(self, suffix: str) -> None: ...
    def suffix(self) -> str: ...


class QProgressBar(QWidget):
    """Progress bar widget with proper typing."""

    valueChanged: Any

    def __init__(self, parent: QWidget | None = None) -> None: ...
    def setValue(self, value: int) -> None: ...
    def value(self) -> int: ...
    def setMinimum(self, min: int) -> None: ...
    def minimum(self) -> int: ...
    def setMaximum(self, max: int) -> None: ...
    def maximum(self) -> int: ...
    def setRange(self, min: int, max: int) -> None: ...
    def reset(self) -> None: ...
    def setFormat(self, format: str) -> None: ...
    def format(self) -> str: ...
    def setTextVisible(self, visible: bool) -> None: ...
    def isTextVisible(self) -> bool: ...


class QProgressDialog(QDialog):
    """Progress dialog with proper typing."""

    canceled: Any

    def __init__(self, labelText: str = "", cancelButtonText: str = "", minimum: int = 0, maximum: int = 100, parent: QWidget | None = None) -> None: ...
    def setValue(self, progress: int) -> None: ...
    def value(self) -> int: ...
    def setLabelText(self, text: str) -> None: ...
    def labelText(self) -> str: ...
    def setCancelButtonText(self, text: str) -> None: ...
    def wasCanceled(self) -> bool: ...
    def setMinimum(self, minimum: int) -> None: ...
    def minimum(self) -> int: ...
    def setMaximum(self, maximum: int) -> None: ...
    def maximum(self) -> int: ...
    def setRange(self, minimum: int, maximum: int) -> None: ...
    def setAutoReset(self, reset: bool) -> None: ...
    def autoReset(self) -> bool: ...
    def setAutoClose(self, close: bool) -> None: ...
    def autoClose(self) -> bool: ...
    def cancel(self) -> None: ...
    def reset(self) -> None: ...
    def setWindowModality(self, modality: Any) -> None: ...
    def setMinimumDuration(self, ms: int) -> None: ...
    def minimumDuration(self) -> int: ...


class QAbstractItemView(QWidget):
    """Abstract item view with proper typing."""

    class SelectionBehavior:
        SelectItems: int
        SelectRows: int
        SelectColumns: int

    class SelectionMode:
        NoSelection: int
        SingleSelection: int
        MultiSelection: int
        ExtendedSelection: int
        ContiguousSelection: int

    class EditTrigger:
        NoEditTriggers: int
        CurrentChanged: int
        DoubleClicked: int
        SelectedClicked: int
        EditKeyPressed: int
        AnyKeyPressed: int
        AllEditTriggers: int

    SelectItems: int
    SelectRows: int
    SelectColumns: int

    SingleSelection: int
    ContiguousSelection: int
    ExtendedSelection: int
    MultiSelection: int
    NoSelection: int

    NoEditTriggers: int
    CurrentChanged: int
    DoubleClicked: int
    SelectedClicked: int
    EditKeyPressed: int
    AnyKeyPressed: int
    AllEditTriggers: int

    def selectionModel(self) -> Any: ...
    def setSelectionModel(self, selectionModel: Any) -> None: ...
    def setSelectionBehavior(self, behavior: int) -> None: ...
    def selectionBehavior(self) -> int: ...
    def setSelectionMode(self, mode: int) -> None: ...
    def selectionMode(self) -> int: ...
    def setEditTriggers(self, triggers: int) -> None: ...
    def editTriggers(self) -> int: ...


class QTableWidget(QAbstractItemView):
    """Table widget with proper typing."""

    cellClicked: Any
    cellDoubleClicked: Any
    itemSelectionChanged: Any
    itemDoubleClicked: Any

    def __init__(self, rows: int = 0, columns: int = 0, parent: QWidget | None = None) -> None: ...
    def setRowCount(self, rows: int) -> None: ...
    def rowCount(self) -> int: ...
    def setColumnCount(self, columns: int) -> None: ...
    def columnCount(self) -> int: ...
    def setItem(self, row: int, column: int, item: Any) -> None: ...
    def item(self, row: int, column: int) -> Any: ...
    def setHorizontalHeaderLabels(self, labels: list[str]) -> None: ...
    def setVerticalHeaderLabels(self, labels: list[str]) -> None: ...
    def horizontalHeader(self) -> Any: ...
    def verticalHeader(self) -> Any: ...
    def clear(self) -> None: ...
    def clearContents(self) -> None: ...
    def currentRow(self) -> int: ...
    def currentColumn(self) -> int: ...
    def setCurrentCell(self, row: int, column: int) -> None: ...
    def selectRow(self, row: int) -> None: ...
    def selectedItems(self) -> list[Any]: ...
    def selectedRanges(self) -> list[Any]: ...
    def insertRow(self, row: int) -> None: ...
    def removeRow(self, row: int) -> None: ...
    def insertColumn(self, column: int) -> None: ...
    def removeColumn(self, column: int) -> None: ...


class QTableWidgetItem:
    """Table widget item with proper typing."""

    def __init__(self, text: str = "") -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setData(self, role: int, value: Any) -> None: ...
    def data(self, role: int) -> Any: ...
    def setFlags(self, flags: Any) -> None: ...
    def flags(self) -> Any: ...
    def setToolTip(self, tip: str) -> None: ...
    def toolTip(self) -> str: ...
    def setTextAlignment(self, alignment: Any) -> None: ...
    def textAlignment(self) -> Any: ...


class QListWidget(QAbstractItemView):
    """List widget with proper typing."""

    itemClicked: Any
    itemDoubleClicked: Any
    itemSelectionChanged: Any
    currentItemChanged: Any
    currentRowChanged: Any

    def __init__(self, parent: QWidget | None = None) -> None: ...
    def addItem(self, item: str | QListWidgetItem) -> None: ...
    def addItems(self, labels: list[str]) -> None: ...
    def insertItem(self, row: int, item: str | QListWidgetItem) -> None: ...
    def item(self, row: int) -> QListWidgetItem | None: ...
    def takeItem(self, row: int) -> QListWidgetItem | None: ...
    def count(self) -> int: ...
    def currentItem(self) -> QListWidgetItem | None: ...
    def setCurrentItem(self, item: QListWidgetItem) -> None: ...
    def currentRow(self) -> int: ...
    def setCurrentRow(self, row: int) -> None: ...
    def row(self, item: QListWidgetItem) -> int: ...
    def clear(self) -> None: ...
    def selectedItems(self) -> list[QListWidgetItem]: ...
    def findItems(self, text: str, flags: Any) -> list[QListWidgetItem]: ...


class QListWidgetItem:
    """List widget item with proper typing."""

    def __init__(self, text: str = "", parent: QListWidget | None = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setData(self, role: int, value: Any) -> None: ...
    def data(self, role: int) -> Any: ...
    def setFlags(self, flags: Any) -> None: ...
    def flags(self) -> Any: ...
    def setIcon(self, icon: Any) -> None: ...
    def icon(self) -> Any: ...
    def setToolTip(self, tip: str) -> None: ...
    def toolTip(self) -> str: ...
    def setSelected(self, select: bool) -> None: ...
    def isSelected(self) -> bool: ...


class QGroupBox(QWidget):
    """Group box widget with proper typing."""

    def __init__(self, title: str = "", parent: QWidget | None = None) -> None: ...
    def setTitle(self, title: str) -> None: ...
    def title(self) -> str: ...
    def setCheckable(self, checkable: bool) -> None: ...
    def isCheckable(self) -> bool: ...
    def setChecked(self, checked: bool) -> None: ...
    def isChecked(self) -> bool: ...


class QSplitter(QWidget):
    """Splitter widget with proper typing."""

    def __init__(self, orientation: Any = None, parent: QWidget | None = None) -> None: ...
    def addWidget(self, widget: QWidget) -> None: ...
    def insertWidget(self, index: int, widget: QWidget) -> None: ...
    def widget(self, index: int) -> QWidget | None: ...
    def count(self) -> int: ...
    def setSizes(self, sizes: list[int]) -> None: ...
    def sizes(self) -> list[int]: ...
    def setOrientation(self, orientation: Any) -> None: ...
    def orientation(self) -> Any: ...
    def setStretchFactor(self, index: int, stretch: int) -> None: ...
    def setCollapsible(self, index: int, collapsible: bool) -> None: ...
    def isCollapsible(self, index: int) -> bool: ...


class QTabWidget(QWidget):
    """Tab widget with proper typing."""

    currentChanged: Any

    def __init__(self, parent: QWidget | None = None) -> None: ...
    def addTab(self, widget: QWidget, label: str) -> int: ...
    def insertTab(self, index: int, widget: QWidget, label: str) -> int: ...
    def removeTab(self, index: int) -> None: ...
    def clear(self) -> None: ...
    def currentIndex(self) -> int: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def currentWidget(self) -> QWidget | None: ...
    def setCurrentWidget(self, widget: QWidget) -> None: ...
    def widget(self, index: int) -> QWidget | None: ...
    def count(self) -> int: ...
    def indexOf(self, widget: QWidget) -> int: ...
    def tabText(self, index: int) -> str: ...
    def setTabText(self, index: int, text: str) -> None: ...
    def setTabEnabled(self, index: int, enabled: bool) -> None: ...
    def isTabEnabled(self, index: int) -> bool: ...


class QScrollArea(QWidget):
    """Scroll area widget with proper typing."""

    def __init__(self, parent: QWidget | None = None) -> None: ...
    def setWidget(self, widget: QWidget) -> None: ...
    def widget(self) -> QWidget | None: ...
    def setWidgetResizable(self, resizable: bool) -> None: ...
    def widgetResizable(self) -> bool: ...
    def setHorizontalScrollBarPolicy(self, policy: Any) -> None: ...
    def horizontalScrollBarPolicy(self) -> Any: ...
    def setVerticalScrollBarPolicy(self, policy: Any) -> None: ...
    def verticalScrollBarPolicy(self) -> Any: ...


class QStackedWidget(QWidget):
    """Stacked widget with proper typing."""

    currentChanged: Any

    def __init__(self, parent: QWidget | None = None) -> None: ...
    def addWidget(self, widget: QWidget) -> int: ...
    def insertWidget(self, index: int, widget: QWidget) -> int: ...
    def removeWidget(self, widget: QWidget) -> None: ...
    def currentIndex(self) -> int: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def currentWidget(self) -> QWidget | None: ...
    def setCurrentWidget(self, widget: QWidget) -> None: ...
    def widget(self, index: int) -> QWidget | None: ...
    def count(self) -> int: ...
    def indexOf(self, widget: QWidget) -> int: ...


class QHeaderView(QWidget):
    """Header view with proper typing."""

    class ResizeMode:
        Interactive: int
        Fixed: int
        Stretch: int
        ResizeToContents: int

    Interactive: int
    Fixed: int
    Stretch: int
    ResizeToContents: int

    def setSectionResizeMode(self, *args: Any) -> None: ...
    def sectionResizeMode(self, logicalIndex: int) -> int: ...
    def setStretchLastSection(self, stretch: bool) -> None: ...
    def stretchLastSection(self) -> bool: ...
    def hideSection(self, logicalIndex: int) -> None: ...
    def showSection(self, logicalIndex: int) -> None: ...
    def isSectionHidden(self, logicalIndex: int) -> bool: ...
    def resizeSection(self, logicalIndex: int, size: int) -> None: ...
    def sectionSize(self, logicalIndex: int) -> int: ...


class QLayout:
    """Base layout class with proper typing."""

    def addWidget(self, widget: QWidget, *args: Any, **kwargs: Any) -> None: ...
    def removeWidget(self, widget: QWidget) -> None: ...
    def addItem(self, item: Any) -> None: ...
    def removeItem(self, item: Any) -> None: ...
    def setContentsMargins(self, left: int, top: int, right: int, bottom: int) -> None: ...
    def contentsMargins(self) -> Any: ...
    def setSpacing(self, spacing: int) -> None: ...
    def spacing(self) -> int: ...
    def count(self) -> int: ...
    def itemAt(self, index: int) -> Any: ...
    def takeAt(self, index: int) -> Any: ...
    def setAlignment(self, *args: Any) -> bool: ...


class QBoxLayout(QLayout):
    """Box layout with proper typing."""

    def __init__(self, direction: Any, parent: QWidget | None = None) -> None: ...
    def addLayout(self, layout: QLayout, stretch: int = 0) -> None: ...
    def insertLayout(self, index: int, layout: QLayout, stretch: int = 0) -> None: ...
    def addStretch(self, stretch: int = 0) -> None: ...
    def insertStretch(self, index: int, stretch: int = 0) -> None: ...
    def addSpacing(self, size: int) -> None: ...
    def insertSpacing(self, index: int, size: int) -> None: ...
    def setStretch(self, index: int, stretch: int) -> None: ...
    def stretch(self, index: int) -> int: ...


class QVBoxLayout(QBoxLayout):
    """Vertical box layout with proper typing."""

    def __init__(self, parent: QWidget | None = None) -> None: ...


class QHBoxLayout(QBoxLayout):
    """Horizontal box layout with proper typing."""

    def __init__(self, parent: QWidget | None = None) -> None: ...


class QFormLayout(QLayout):
    """Form layout with proper typing."""

    def __init__(self, parent: QWidget | None = None) -> None: ...
    def addRow(self, *args: Any) -> None: ...
    def insertRow(self, row: int, *args: Any) -> None: ...
    def removeRow(self, row: int) -> None: ...
    def rowCount(self) -> int: ...
    def setLabelAlignment(self, alignment: Any) -> None: ...
    def labelAlignment(self) -> Any: ...
    def setFormAlignment(self, alignment: Any) -> None: ...
    def formAlignment(self) -> Any: ...


class QGridLayout(QLayout):
    """Grid layout with proper typing."""

    def __init__(self, parent: QWidget | None = None) -> None: ...
    def addWidget(self, widget: QWidget, row: int = 0, column: int = 0, rowSpan: int = 1, columnSpan: int = 1, alignment: Any = None) -> None: ...
    def addLayout(self, layout: QLayout, row: int, column: int, rowSpan: int = 1, columnSpan: int = 1, alignment: Any = None) -> None: ...
    def setRowStretch(self, row: int, stretch: int) -> None: ...
    def rowStretch(self, row: int) -> int: ...
    def setColumnStretch(self, column: int, stretch: int) -> None: ...
    def columnStretch(self, column: int) -> int: ...
    def setRowMinimumHeight(self, row: int, minSize: int) -> None: ...
    def rowMinimumHeight(self, row: int) -> int: ...
    def setColumnMinimumWidth(self, column: int, minSize: int) -> None: ...
    def columnMinimumWidth(self, column: int) -> int: ...


class QDialogButtonBox(QWidget):
    """Dialog button box with proper typing."""

    class StandardButton:
        NoButton: int
        Ok: int
        Save: int
        SaveAll: int
        Open: int
        Yes: int
        YesToAll: int
        No: int
        NoToAll: int
        Abort: int
        Retry: int
        Ignore: int
        Close: int
        Cancel: int
        Discard: int
        Help: int
        Apply: int
        Reset: int
        RestoreDefaults: int

    NoButton: int
    Ok: int
    Cancel: int
    Yes: int
    No: int
    Apply: int
    Close: int
    Reset: int
    Help: int
    Save: int
    Open: int
    Discard: int
    RestoreDefaults: int

    accepted: Any
    rejected: Any
    clicked: Any

    def __init__(self, *args: Any, parent: QWidget | None = None) -> None: ...
    def addButton(self, *args: Any) -> QPushButton: ...
    def button(self, which: int) -> QPushButton | None: ...
    def buttons(self) -> list[QPushButton]: ...
    def clear(self) -> None: ...
    def setStandardButtons(self, buttons: int) -> None: ...
    def standardButtons(self) -> int: ...


class QMessageBox(QDialog):
    """Message box dialog with proper typing."""

    class StandardButton:
        NoButton: int
        Ok: int
        Save: int
        SaveAll: int
        Open: int
        Yes: int
        YesToAll: int
        No: int
        NoToAll: int
        Abort: int
        Retry: int
        Ignore: int
        Close: int
        Cancel: int
        Discard: int
        Help: int
        Apply: int
        Reset: int
        RestoreDefaults: int

    NoIcon: int
    Information: int
    Warning: int
    Critical: int
    Question: int

    NoButton: int
    Ok: int
    Cancel: int
    Yes: int
    No: int

    @staticmethod
    def information(parent: QWidget | None, title: str, text: str, buttons: int = ...) -> int: ...
    @staticmethod
    def warning(parent: QWidget | None, title: str, text: str, buttons: int = ...) -> int: ...
    @staticmethod
    def critical(parent: QWidget | None, title: str, text: str, buttons: int = ...) -> int: ...
    @staticmethod
    def question(parent: QWidget | None, title: str, text: str, buttons: int = ...) -> int: ...


class QFileDialog(QDialog):
    """File dialog with proper typing."""

    @staticmethod
    def getOpenFileName(parent: QWidget | None = None, caption: str = "", directory: str = "", filter: str = "", *args: Any) -> tuple[str, str]: ...
    @staticmethod
    def getOpenFileNames(parent: QWidget | None = None, caption: str = "", directory: str = "", filter: str = "", *args: Any) -> tuple[list[str], str]: ...
    @staticmethod
    def getSaveFileName(parent: QWidget | None = None, caption: str = "", directory: str = "", filter: str = "", *args: Any) -> tuple[str, str]: ...
    @staticmethod
    def getExistingDirectory(parent: QWidget | None = None, caption: str = "", directory: str = "", *args: Any) -> str: ...


class QInputDialog(QDialog):
    """Input dialog with proper typing."""

    @staticmethod
    def getText(parent: QWidget | None, title: str, label: str, *args: Any) -> tuple[str, bool]: ...
    @staticmethod
    def getInt(parent: QWidget | None, title: str, label: str, *args: Any) -> tuple[int, bool]: ...
    @staticmethod
    def getDouble(parent: QWidget | None, title: str, label: str, *args: Any) -> tuple[float, bool]: ...
    @staticmethod
    def getItem(parent: QWidget | None, title: str, label: str, items: list[str], *args: Any) -> tuple[str, bool]: ...


class QApplication:
    """Application class with proper typing."""

    def __init__(self, args: list[str]) -> None: ...
    def exec(self) -> int: ...
    @staticmethod
    def instance() -> QApplication | None: ...
    @staticmethod
    def processEvents() -> None: ...
    @staticmethod
    def quit() -> None: ...
    @staticmethod
    def setStyle(style: Any) -> None: ...
    @staticmethod
    def style() -> Any: ...
    @staticmethod
    def setFont(font: Any) -> None: ...
    @staticmethod
    def font() -> Any: ...
    @staticmethod
    def setPalette(palette: Any) -> None: ...
    @staticmethod
    def palette() -> Any: ...


class QStatusBar(QWidget):
    """Status bar with proper typing."""

    def __init__(self, parent: QWidget | None = None) -> None: ...
    def showMessage(self, message: str, timeout: int = 0) -> None: ...
    def currentMessage(self) -> str: ...
    def clearMessage(self) -> None: ...
    def addWidget(self, widget: QWidget, stretch: int = 0) -> None: ...
    def addPermanentWidget(self, widget: QWidget, stretch: int = 0) -> None: ...
    def removeWidget(self, widget: QWidget) -> None: ...


class QToolBar(QWidget):
    """Tool bar with proper typing."""

    def __init__(self, title: str = "", parent: QWidget | None = None) -> None: ...
    def addAction(self, *args: Any) -> Any: ...
    def addSeparator(self) -> Any: ...
    def addWidget(self, widget: QWidget) -> Any: ...
    def clear(self) -> None: ...
    def setMovable(self, movable: bool) -> None: ...
    def isMovable(self) -> bool: ...
    def setFloatable(self, floatable: bool) -> None: ...
    def isFloatable(self) -> bool: ...


class QMenu(QWidget):
    """Menu widget with proper typing."""

    triggered: Any

    def __init__(self, title: str = "", parent: QWidget | None = None) -> None: ...
    def addAction(self, *args: Any) -> Any: ...
    def addMenu(self, *args: Any) -> Any: ...
    def addSeparator(self) -> Any: ...
    def clear(self) -> None: ...
    def exec(self, *args: Any) -> Any: ...
    def popup(self, pos: Any) -> None: ...


class QMenuBar(QWidget):
    """Menu bar with proper typing."""

    def __init__(self, parent: QWidget | None = None) -> None: ...
    def addMenu(self, *args: Any) -> QMenu: ...
    def addAction(self, *args: Any) -> Any: ...
    def clear(self) -> None: ...
